version: "3.1"
services:
    undisclosedweb:
        build: .
        ports: 
            - "44512:80"
        volumes:
            - ./undisclosedweb:/var/www/html:ro
            - ./nft-collection:/nft-collection:ro
        networks:
            - default
    
    adminbrain:
        build: ./admin_brain
        ports:
            - 39981:3000
volumes:
    persistent:




